# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f07f4bf22b8e4c2a84282b189c881f5e98fda3b454febe94f5569387decdc9479a6ee23400ffbde4228141d157a5cb1b49c6de124be114b0e6b0439c3fcf0ab

test:
  secret_key_base: 6f2dbc1ea1f9151b914a9fff45a460da22ff010582940a320f20518ca39bb9aac992575fbe6e3f18566d39bfecaa3f9f269837d80de63768288b0bfc04c7ea11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
